#!/bin/sh
#
# Start/stop the SWARMS daemons
#

set -e

case "$1" in
  start) 
        echo -n "Starting SWARMSd: " 
        start-stop-daemon -S -b -n SWARMSd -a /home/root/alex/drivePy/launchDrivePy.sh
        echo "done" 
        ;; 
  stop) 
        echo -n "Stopping SWARMSd: " 
	echo 0 > /sys/class/leds/beagleboard\:\:usr1/brightness
	start-stop-daemon -K -n SWARMSd 
 	killall python
        echo "done" 
        ;; 
  restart) 
        $0 stop 
        $0 start 
        ;; 
  *) 
        echo "Usage: SWARMSInit { start | stop | restart }" >&2 
        exit 1 
        ;; 
esac 
 
exit 0


